language: python
python:
  - "3.6"

jobs:
  include:
    - stage: build
      name: "Wait for heroku to finish"
      script: 
      - sleep 150
    - stage: test
      script: python3 test.py

