language: python
python:
  - "3.6"

services:
  - docker

before_script: 
- pip install docker-compose
- chmod +x Test.sh

jobs:
  include:
    - stage: build
      name: "Build"
      env: ISOLATED=true
      script: 
      - docker build -t flask-api:latest .
    - stage: test
      env: ISOLATED=true
      script: bash ~/Test.sh

